//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SkylineUploader.PricingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PricingServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PricingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAssemblyVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddMediaBandingItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMediaItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddBandingItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckGloalProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptionPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomOptionTitlesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOptionPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindMedisItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback PricingAddEditSingleMediaItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePricingProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptionsByPortalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMediaItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOptionItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMediaByPortalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsByPortalOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddExistingPorductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPortalGuidFromUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback UseHttpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PricingService() {
            this.Url = global::SkylineUploader.Properties.Settings.Default.SkylineUploader_PricingService_PricingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAssemblyVersionCompletedEventHandler GetAssemblyVersionCompleted;
        
        /// <remarks/>
        public event AddMediaBandingItemCompletedEventHandler AddMediaBandingItemCompleted;
        
        /// <remarks/>
        public event DeleteMediaItemsCompletedEventHandler DeleteMediaItemsCompleted;
        
        /// <remarks/>
        public event AddBandingItemCompletedEventHandler AddBandingItemCompleted;
        
        /// <remarks/>
        public event DeleteItemsCompletedEventHandler DeleteItemsCompleted;
        
        /// <remarks/>
        public event CheckGloalProductsCompletedEventHandler CheckGloalProductsCompleted;
        
        /// <remarks/>
        public event GetOptionPriceCompletedEventHandler GetOptionPriceCompleted;
        
        /// <remarks/>
        public event GetCustomOptionTitlesCompletedEventHandler GetCustomOptionTitlesCompleted;
        
        /// <remarks/>
        public event UpdateOptionPriceCompletedEventHandler UpdateOptionPriceCompleted;
        
        /// <remarks/>
        public event FindMedisItemCompletedEventHandler FindMedisItemCompleted;
        
        /// <remarks/>
        public event PricingAddEditSingleMediaItemCompletedEventHandler PricingAddEditSingleMediaItemCompleted;
        
        /// <remarks/>
        public event UpdatePricingProductCompletedEventHandler UpdatePricingProductCompleted;
        
        /// <remarks/>
        public event GetOptionsByPortalCompletedEventHandler GetOptionsByPortalCompleted;
        
        /// <remarks/>
        public event GetMediaItemCompletedEventHandler GetMediaItemCompleted;
        
        /// <remarks/>
        public event GetOptionItemsCompletedEventHandler GetOptionItemsCompleted;
        
        /// <remarks/>
        public event GetMediaByPortalCompletedEventHandler GetMediaByPortalCompleted;
        
        /// <remarks/>
        public event GetProductsByPortalCompletedEventHandler GetProductsByPortalCompleted;
        
        /// <remarks/>
        public event AddExistingPorductsCompletedEventHandler AddExistingPorductsCompleted;
        
        /// <remarks/>
        public event GetPortalGuidFromUrlCompletedEventHandler GetPortalGuidFromUrlCompleted;
        
        /// <remarks/>
        public event UseHttpsCompletedEventHandler UseHttpsCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAssemblyVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAssemblyVersion() {
            object[] results = this.Invoke("GetAssemblyVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAssemblyVersionAsync() {
            this.GetAssemblyVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetAssemblyVersionAsync(object userState) {
            if ((this.GetAssemblyVersionOperationCompleted == null)) {
                this.GetAssemblyVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAssemblyVersionOperationCompleted);
            }
            this.InvokeAsync("GetAssemblyVersion", new object[0], this.GetAssemblyVersionOperationCompleted, userState);
        }
        
        private void OnGetAssemblyVersionOperationCompleted(object arg) {
            if ((this.GetAssemblyVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAssemblyVersionCompleted(this, new GetAssemblyVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddMediaBandingItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddMediaBandingItem(System.Guid mediaId, System.Guid portalId, int from, int to, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost, int printerType) {
            object[] results = this.Invoke("AddMediaBandingItem", new object[] {
                        mediaId,
                        portalId,
                        from,
                        to,
                        colourSingleSided,
                        colourDoubleSided,
                        monoSingleSided,
                        monoDoubleSided,
                        mediaCost,
                        laminatingCost,
                        printerType});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddMediaBandingItemAsync(System.Guid mediaId, System.Guid portalId, int from, int to, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost, int printerType) {
            this.AddMediaBandingItemAsync(mediaId, portalId, from, to, colourSingleSided, colourDoubleSided, monoSingleSided, monoDoubleSided, mediaCost, laminatingCost, printerType, null);
        }
        
        /// <remarks/>
        public void AddMediaBandingItemAsync(System.Guid mediaId, System.Guid portalId, int from, int to, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost, int printerType, object userState) {
            if ((this.AddMediaBandingItemOperationCompleted == null)) {
                this.AddMediaBandingItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddMediaBandingItemOperationCompleted);
            }
            this.InvokeAsync("AddMediaBandingItem", new object[] {
                        mediaId,
                        portalId,
                        from,
                        to,
                        colourSingleSided,
                        colourDoubleSided,
                        monoSingleSided,
                        monoDoubleSided,
                        mediaCost,
                        laminatingCost,
                        printerType}, this.AddMediaBandingItemOperationCompleted, userState);
        }
        
        private void OnAddMediaBandingItemOperationCompleted(object arg) {
            if ((this.AddMediaBandingItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddMediaBandingItemCompleted(this, new AddMediaBandingItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMediaItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMediaItems(System.Guid mediaId, int printerType) {
            object[] results = this.Invoke("DeleteMediaItems", new object[] {
                        mediaId,
                        printerType});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMediaItemsAsync(System.Guid mediaId, int printerType) {
            this.DeleteMediaItemsAsync(mediaId, printerType, null);
        }
        
        /// <remarks/>
        public void DeleteMediaItemsAsync(System.Guid mediaId, int printerType, object userState) {
            if ((this.DeleteMediaItemsOperationCompleted == null)) {
                this.DeleteMediaItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMediaItemsOperationCompleted);
            }
            this.InvokeAsync("DeleteMediaItems", new object[] {
                        mediaId,
                        printerType}, this.DeleteMediaItemsOperationCompleted, userState);
        }
        
        private void OnDeleteMediaItemsOperationCompleted(object arg) {
            if ((this.DeleteMediaItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMediaItemsCompleted(this, new DeleteMediaItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBandingItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddBandingItem(System.Guid elementId, System.Guid portalId, string name, string value, string type, decimal price, int order, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> from, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> to) {
            object[] results = this.Invoke("AddBandingItem", new object[] {
                        elementId,
                        portalId,
                        name,
                        value,
                        type,
                        price,
                        order,
                        from,
                        to});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddBandingItemAsync(System.Guid elementId, System.Guid portalId, string name, string value, string type, decimal price, int order, System.Nullable<int> from, System.Nullable<int> to) {
            this.AddBandingItemAsync(elementId, portalId, name, value, type, price, order, from, to, null);
        }
        
        /// <remarks/>
        public void AddBandingItemAsync(System.Guid elementId, System.Guid portalId, string name, string value, string type, decimal price, int order, System.Nullable<int> from, System.Nullable<int> to, object userState) {
            if ((this.AddBandingItemOperationCompleted == null)) {
                this.AddBandingItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddBandingItemOperationCompleted);
            }
            this.InvokeAsync("AddBandingItem", new object[] {
                        elementId,
                        portalId,
                        name,
                        value,
                        type,
                        price,
                        order,
                        from,
                        to}, this.AddBandingItemOperationCompleted, userState);
        }
        
        private void OnAddBandingItemOperationCompleted(object arg) {
            if ((this.AddBandingItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddBandingItemCompleted(this, new AddBandingItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteItems(System.Guid elementId) {
            object[] results = this.Invoke("DeleteItems", new object[] {
                        elementId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteItemsAsync(System.Guid elementId) {
            this.DeleteItemsAsync(elementId, null);
        }
        
        /// <remarks/>
        public void DeleteItemsAsync(System.Guid elementId, object userState) {
            if ((this.DeleteItemsOperationCompleted == null)) {
                this.DeleteItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteItemsOperationCompleted);
            }
            this.InvokeAsync("DeleteItems", new object[] {
                        elementId}, this.DeleteItemsOperationCompleted, userState);
        }
        
        private void OnDeleteItemsOperationCompleted(object arg) {
            if ((this.DeleteItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteItemsCompleted(this, new DeleteItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckGloalProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckGloalProducts() {
            object[] results = this.Invoke("CheckGloalProducts", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckGloalProductsAsync() {
            this.CheckGloalProductsAsync(null);
        }
        
        /// <remarks/>
        public void CheckGloalProductsAsync(object userState) {
            if ((this.CheckGloalProductsOperationCompleted == null)) {
                this.CheckGloalProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckGloalProductsOperationCompleted);
            }
            this.InvokeAsync("CheckGloalProducts", new object[0], this.CheckGloalProductsOperationCompleted, userState);
        }
        
        private void OnCheckGloalProductsOperationCompleted(object arg) {
            if ((this.CheckGloalProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckGloalProductsCompleted(this, new CheckGloalProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOptionPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal GetOptionPrice(string type, string name, System.Guid portalId) {
            object[] results = this.Invoke("GetOptionPrice", new object[] {
                        type,
                        name,
                        portalId});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetOptionPriceAsync(string type, string name, System.Guid portalId) {
            this.GetOptionPriceAsync(type, name, portalId, null);
        }
        
        /// <remarks/>
        public void GetOptionPriceAsync(string type, string name, System.Guid portalId, object userState) {
            if ((this.GetOptionPriceOperationCompleted == null)) {
                this.GetOptionPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptionPriceOperationCompleted);
            }
            this.InvokeAsync("GetOptionPrice", new object[] {
                        type,
                        name,
                        portalId}, this.GetOptionPriceOperationCompleted, userState);
        }
        
        private void OnGetOptionPriceOperationCompleted(object arg) {
            if ((this.GetOptionPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptionPriceCompleted(this, new GetOptionPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomOptionTitles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomOptionTitle[] GetCustomOptionTitles(System.Guid portalId) {
            object[] results = this.Invoke("GetCustomOptionTitles", new object[] {
                        portalId});
            return ((CustomOptionTitle[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomOptionTitlesAsync(System.Guid portalId) {
            this.GetCustomOptionTitlesAsync(portalId, null);
        }
        
        /// <remarks/>
        public void GetCustomOptionTitlesAsync(System.Guid portalId, object userState) {
            if ((this.GetCustomOptionTitlesOperationCompleted == null)) {
                this.GetCustomOptionTitlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomOptionTitlesOperationCompleted);
            }
            this.InvokeAsync("GetCustomOptionTitles", new object[] {
                        portalId}, this.GetCustomOptionTitlesOperationCompleted, userState);
        }
        
        private void OnGetCustomOptionTitlesOperationCompleted(object arg) {
            if ((this.GetCustomOptionTitlesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomOptionTitlesCompleted(this, new GetCustomOptionTitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOptionPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateOptionPrice(System.Guid elementId, decimal price) {
            object[] results = this.Invoke("UpdateOptionPrice", new object[] {
                        elementId,
                        price});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOptionPriceAsync(System.Guid elementId, decimal price) {
            this.UpdateOptionPriceAsync(elementId, price, null);
        }
        
        /// <remarks/>
        public void UpdateOptionPriceAsync(System.Guid elementId, decimal price, object userState) {
            if ((this.UpdateOptionPriceOperationCompleted == null)) {
                this.UpdateOptionPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOptionPriceOperationCompleted);
            }
            this.InvokeAsync("UpdateOptionPrice", new object[] {
                        elementId,
                        price}, this.UpdateOptionPriceOperationCompleted, userState);
        }
        
        private void OnUpdateOptionPriceOperationCompleted(object arg) {
            if ((this.UpdateOptionPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOptionPriceCompleted(this, new UpdateOptionPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FindMedisItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PricingMedium FindMedisItem(string paperName, System.Guid portalId, int qty, int printType, bool globalPricing) {
            object[] results = this.Invoke("FindMedisItem", new object[] {
                        paperName,
                        portalId,
                        qty,
                        printType,
                        globalPricing});
            return ((PricingMedium)(results[0]));
        }
        
        /// <remarks/>
        public void FindMedisItemAsync(string paperName, System.Guid portalId, int qty, int printType, bool globalPricing) {
            this.FindMedisItemAsync(paperName, portalId, qty, printType, globalPricing, null);
        }
        
        /// <remarks/>
        public void FindMedisItemAsync(string paperName, System.Guid portalId, int qty, int printType, bool globalPricing, object userState) {
            if ((this.FindMedisItemOperationCompleted == null)) {
                this.FindMedisItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindMedisItemOperationCompleted);
            }
            this.InvokeAsync("FindMedisItem", new object[] {
                        paperName,
                        portalId,
                        qty,
                        printType,
                        globalPricing}, this.FindMedisItemOperationCompleted, userState);
        }
        
        private void OnFindMedisItemOperationCompleted(object arg) {
            if ((this.FindMedisItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindMedisItemCompleted(this, new FindMedisItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PricingAddEditSingleMediaItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PricingAddEditSingleMediaItem(System.Guid mediaId, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost) {
            object[] results = this.Invoke("PricingAddEditSingleMediaItem", new object[] {
                        mediaId,
                        colourSingleSided,
                        colourDoubleSided,
                        monoSingleSided,
                        monoDoubleSided,
                        mediaCost,
                        laminatingCost});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PricingAddEditSingleMediaItemAsync(System.Guid mediaId, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost) {
            this.PricingAddEditSingleMediaItemAsync(mediaId, colourSingleSided, colourDoubleSided, monoSingleSided, monoDoubleSided, mediaCost, laminatingCost, null);
        }
        
        /// <remarks/>
        public void PricingAddEditSingleMediaItemAsync(System.Guid mediaId, decimal colourSingleSided, decimal colourDoubleSided, decimal monoSingleSided, decimal monoDoubleSided, decimal mediaCost, decimal laminatingCost, object userState) {
            if ((this.PricingAddEditSingleMediaItemOperationCompleted == null)) {
                this.PricingAddEditSingleMediaItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPricingAddEditSingleMediaItemOperationCompleted);
            }
            this.InvokeAsync("PricingAddEditSingleMediaItem", new object[] {
                        mediaId,
                        colourSingleSided,
                        colourDoubleSided,
                        monoSingleSided,
                        monoDoubleSided,
                        mediaCost,
                        laminatingCost}, this.PricingAddEditSingleMediaItemOperationCompleted, userState);
        }
        
        private void OnPricingAddEditSingleMediaItemOperationCompleted(object arg) {
            if ((this.PricingAddEditSingleMediaItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PricingAddEditSingleMediaItemCompleted(this, new PricingAddEditSingleMediaItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePricingProduct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePricingProduct(System.Guid pricingProductId, bool calcPrice, bool fixedPrice, decimal priceEach, double markUp, double taxRate) {
            object[] results = this.Invoke("UpdatePricingProduct", new object[] {
                        pricingProductId,
                        calcPrice,
                        fixedPrice,
                        priceEach,
                        markUp,
                        taxRate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePricingProductAsync(System.Guid pricingProductId, bool calcPrice, bool fixedPrice, decimal priceEach, double markUp, double taxRate) {
            this.UpdatePricingProductAsync(pricingProductId, calcPrice, fixedPrice, priceEach, markUp, taxRate, null);
        }
        
        /// <remarks/>
        public void UpdatePricingProductAsync(System.Guid pricingProductId, bool calcPrice, bool fixedPrice, decimal priceEach, double markUp, double taxRate, object userState) {
            if ((this.UpdatePricingProductOperationCompleted == null)) {
                this.UpdatePricingProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePricingProductOperationCompleted);
            }
            this.InvokeAsync("UpdatePricingProduct", new object[] {
                        pricingProductId,
                        calcPrice,
                        fixedPrice,
                        priceEach,
                        markUp,
                        taxRate}, this.UpdatePricingProductOperationCompleted, userState);
        }
        
        private void OnUpdatePricingProductOperationCompleted(object arg) {
            if ((this.UpdatePricingProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePricingProductCompleted(this, new UpdatePricingProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOptionsByPortal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PricingOptions[] GetOptionsByPortal(System.Guid portalId) {
            object[] results = this.Invoke("GetOptionsByPortal", new object[] {
                        portalId});
            return ((PricingOptions[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOptionsByPortalAsync(System.Guid portalId) {
            this.GetOptionsByPortalAsync(portalId, null);
        }
        
        /// <remarks/>
        public void GetOptionsByPortalAsync(System.Guid portalId, object userState) {
            if ((this.GetOptionsByPortalOperationCompleted == null)) {
                this.GetOptionsByPortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptionsByPortalOperationCompleted);
            }
            this.InvokeAsync("GetOptionsByPortal", new object[] {
                        portalId}, this.GetOptionsByPortalOperationCompleted, userState);
        }
        
        private void OnGetOptionsByPortalOperationCompleted(object arg) {
            if ((this.GetOptionsByPortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptionsByPortalCompleted(this, new GetOptionsByPortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMediaItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PricingGetMediaItemResultSet[] GetMediaItem(System.Guid mediaItemId, int printerType) {
            object[] results = this.Invoke("GetMediaItem", new object[] {
                        mediaItemId,
                        printerType});
            return ((PricingGetMediaItemResultSet[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMediaItemAsync(System.Guid mediaItemId, int printerType) {
            this.GetMediaItemAsync(mediaItemId, printerType, null);
        }
        
        /// <remarks/>
        public void GetMediaItemAsync(System.Guid mediaItemId, int printerType, object userState) {
            if ((this.GetMediaItemOperationCompleted == null)) {
                this.GetMediaItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMediaItemOperationCompleted);
            }
            this.InvokeAsync("GetMediaItem", new object[] {
                        mediaItemId,
                        printerType}, this.GetMediaItemOperationCompleted, userState);
        }
        
        private void OnGetMediaItemOperationCompleted(object arg) {
            if ((this.GetMediaItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMediaItemCompleted(this, new GetMediaItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOptionItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OptionCost[] GetOptionItems(System.Guid elementId, System.Guid portalId) {
            object[] results = this.Invoke("GetOptionItems", new object[] {
                        elementId,
                        portalId});
            return ((OptionCost[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOptionItemsAsync(System.Guid elementId, System.Guid portalId) {
            this.GetOptionItemsAsync(elementId, portalId, null);
        }
        
        /// <remarks/>
        public void GetOptionItemsAsync(System.Guid elementId, System.Guid portalId, object userState) {
            if ((this.GetOptionItemsOperationCompleted == null)) {
                this.GetOptionItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOptionItemsOperationCompleted);
            }
            this.InvokeAsync("GetOptionItems", new object[] {
                        elementId,
                        portalId}, this.GetOptionItemsOperationCompleted, userState);
        }
        
        private void OnGetOptionItemsOperationCompleted(object arg) {
            if ((this.GetOptionItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOptionItemsCompleted(this, new GetOptionItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMediaByPortal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MediaCosting[] GetMediaByPortal(System.Guid portalId, int printerId) {
            object[] results = this.Invoke("GetMediaByPortal", new object[] {
                        portalId,
                        printerId});
            return ((MediaCosting[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMediaByPortalAsync(System.Guid portalId, int printerId) {
            this.GetMediaByPortalAsync(portalId, printerId, null);
        }
        
        /// <remarks/>
        public void GetMediaByPortalAsync(System.Guid portalId, int printerId, object userState) {
            if ((this.GetMediaByPortalOperationCompleted == null)) {
                this.GetMediaByPortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMediaByPortalOperationCompleted);
            }
            this.InvokeAsync("GetMediaByPortal", new object[] {
                        portalId,
                        printerId}, this.GetMediaByPortalOperationCompleted, userState);
        }
        
        private void OnGetMediaByPortalOperationCompleted(object arg) {
            if ((this.GetMediaByPortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMediaByPortalCompleted(this, new GetMediaByPortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductsByPortal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProductCost[] GetProductsByPortal(System.Guid portalId) {
            object[] results = this.Invoke("GetProductsByPortal", new object[] {
                        portalId});
            return ((ProductCost[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsByPortalAsync(System.Guid portalId) {
            this.GetProductsByPortalAsync(portalId, null);
        }
        
        /// <remarks/>
        public void GetProductsByPortalAsync(System.Guid portalId, object userState) {
            if ((this.GetProductsByPortalOperationCompleted == null)) {
                this.GetProductsByPortalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsByPortalOperationCompleted);
            }
            this.InvokeAsync("GetProductsByPortal", new object[] {
                        portalId}, this.GetProductsByPortalOperationCompleted, userState);
        }
        
        private void OnGetProductsByPortalOperationCompleted(object arg) {
            if ((this.GetProductsByPortalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsByPortalCompleted(this, new GetProductsByPortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddExistingPorducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddExistingPorducts(System.Guid portalId) {
            object[] results = this.Invoke("AddExistingPorducts", new object[] {
                        portalId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddExistingPorductsAsync(System.Guid portalId) {
            this.AddExistingPorductsAsync(portalId, null);
        }
        
        /// <remarks/>
        public void AddExistingPorductsAsync(System.Guid portalId, object userState) {
            if ((this.AddExistingPorductsOperationCompleted == null)) {
                this.AddExistingPorductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddExistingPorductsOperationCompleted);
            }
            this.InvokeAsync("AddExistingPorducts", new object[] {
                        portalId}, this.AddExistingPorductsOperationCompleted, userState);
        }
        
        private void OnAddExistingPorductsOperationCompleted(object arg) {
            if ((this.AddExistingPorductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddExistingPorductsCompleted(this, new AddExistingPorductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPortalGuidFromUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid GetPortalGuidFromUrl(string url) {
            object[] results = this.Invoke("GetPortalGuidFromUrl", new object[] {
                        url});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void GetPortalGuidFromUrlAsync(string url) {
            this.GetPortalGuidFromUrlAsync(url, null);
        }
        
        /// <remarks/>
        public void GetPortalGuidFromUrlAsync(string url, object userState) {
            if ((this.GetPortalGuidFromUrlOperationCompleted == null)) {
                this.GetPortalGuidFromUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPortalGuidFromUrlOperationCompleted);
            }
            this.InvokeAsync("GetPortalGuidFromUrl", new object[] {
                        url}, this.GetPortalGuidFromUrlOperationCompleted, userState);
        }
        
        private void OnGetPortalGuidFromUrlOperationCompleted(object arg) {
            if ((this.GetPortalGuidFromUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPortalGuidFromUrlCompleted(this, new GetPortalGuidFromUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UseHttps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UseHttps(System.Guid portalId) {
            object[] results = this.Invoke("UseHttps", new object[] {
                        portalId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UseHttpsAsync(System.Guid portalId) {
            this.UseHttpsAsync(portalId, null);
        }
        
        /// <remarks/>
        public void UseHttpsAsync(System.Guid portalId, object userState) {
            if ((this.UseHttpsOperationCompleted == null)) {
                this.UseHttpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUseHttpsOperationCompleted);
            }
            this.InvokeAsync("UseHttps", new object[] {
                        portalId}, this.UseHttpsOperationCompleted, userState);
        }
        
        private void OnUseHttpsOperationCompleted(object arg) {
            if ((this.UseHttpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UseHttpsCompleted(this, new UseHttpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid ValidateUser(string username, string password, out bool validUser, out bool globalUser) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        username,
                        password});
            validUser = ((bool)(results[1]));
            globalUser = ((bool)(results[2]));
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password) {
            this.ValidateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string username, string password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        username,
                        password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomOptionTitle {
        
        private string elementTypeField;
        
        private string titleField;
        
        private string controlTypeField;
        
        /// <remarks/>
        public string ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string ControlType {
            get {
                return this.controlTypeField;
            }
            set {
                this.controlTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductCost {
        
        private System.Guid pricingProductIdField;
        
        private string nameField;
        
        private bool calculatedPriceField;
        
        private bool fixedPriceField;
        
        private decimal priceEachField;
        
        private double markupField;
        
        private double taxRateField;
        
        /// <remarks/>
        public System.Guid PricingProductId {
            get {
                return this.pricingProductIdField;
            }
            set {
                this.pricingProductIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool CalculatedPrice {
            get {
                return this.calculatedPriceField;
            }
            set {
                this.calculatedPriceField = value;
            }
        }
        
        /// <remarks/>
        public bool FixedPrice {
            get {
                return this.fixedPriceField;
            }
            set {
                this.fixedPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal PriceEach {
            get {
                return this.priceEachField;
            }
            set {
                this.priceEachField = value;
            }
        }
        
        /// <remarks/>
        public double Markup {
            get {
                return this.markupField;
            }
            set {
                this.markupField = value;
            }
        }
        
        /// <remarks/>
        public double TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MediaCosting {
        
        private System.Guid pricingMediaIdField;
        
        private System.Guid controlItemIdField;
        
        private int qtyFromField;
        
        private int qtyToField;
        
        private string nameField;
        
        private decimal colourSingleSidedField;
        
        private decimal colourDoubleSidedField;
        
        private decimal monoSingleSidedField;
        
        private decimal monoDoubleSidedField;
        
        private decimal mediaCostField;
        
        private decimal laminatingCostField;
        
        /// <remarks/>
        public System.Guid PricingMediaId {
            get {
                return this.pricingMediaIdField;
            }
            set {
                this.pricingMediaIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ControlItemId {
            get {
                return this.controlItemIdField;
            }
            set {
                this.controlItemIdField = value;
            }
        }
        
        /// <remarks/>
        public int QtyFrom {
            get {
                return this.qtyFromField;
            }
            set {
                this.qtyFromField = value;
            }
        }
        
        /// <remarks/>
        public int QtyTo {
            get {
                return this.qtyToField;
            }
            set {
                this.qtyToField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourSingleSided {
            get {
                return this.colourSingleSidedField;
            }
            set {
                this.colourSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourDoubleSided {
            get {
                return this.colourDoubleSidedField;
            }
            set {
                this.colourDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoSingleSided {
            get {
                return this.monoSingleSidedField;
            }
            set {
                this.monoSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoDoubleSided {
            get {
                return this.monoDoubleSidedField;
            }
            set {
                this.monoDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MediaCost {
            get {
                return this.mediaCostField;
            }
            set {
                this.mediaCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal LaminatingCost {
            get {
                return this.laminatingCostField;
            }
            set {
                this.laminatingCostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OptionCost {
        
        private System.Guid pricingOptionIdField;
        
        private System.Guid elementIdField;
        
        private System.Guid portalIdField;
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        private decimal priceField;
        
        private int orderField;
        
        private System.Nullable<int> qtyFromField;
        
        private System.Nullable<int> qtyToField;
        
        /// <remarks/>
        public System.Guid PricingOptionId {
            get {
                return this.pricingOptionIdField;
            }
            set {
                this.pricingOptionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ElementId {
            get {
                return this.elementIdField;
            }
            set {
                this.elementIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtyFrom {
            get {
                return this.qtyFromField;
            }
            set {
                this.qtyFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtyTo {
            get {
                return this.qtyToField;
            }
            set {
                this.qtyToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PricingGetMediaItemResultSet {
        
        private int qtyFromField;
        
        private int qtyToField;
        
        private decimal colourSingleSidedField;
        
        private decimal colourDoubleSidedField;
        
        private decimal monoSingleSidedField;
        
        private decimal monoDoubleSidedField;
        
        private decimal mediaCostField;
        
        private decimal laminatingCostField;
        
        /// <remarks/>
        public int QtyFrom {
            get {
                return this.qtyFromField;
            }
            set {
                this.qtyFromField = value;
            }
        }
        
        /// <remarks/>
        public int QtyTo {
            get {
                return this.qtyToField;
            }
            set {
                this.qtyToField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourSingleSided {
            get {
                return this.colourSingleSidedField;
            }
            set {
                this.colourSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourDoubleSided {
            get {
                return this.colourDoubleSidedField;
            }
            set {
                this.colourDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoSingleSided {
            get {
                return this.monoSingleSidedField;
            }
            set {
                this.monoSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoDoubleSided {
            get {
                return this.monoDoubleSidedField;
            }
            set {
                this.monoDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MediaCost {
            get {
                return this.mediaCostField;
            }
            set {
                this.mediaCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal LaminatingCost {
            get {
                return this.laminatingCostField;
            }
            set {
                this.laminatingCostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PricingOptions {
        
        private System.Guid pricingOptionIdField;
        
        private System.Guid elementIdField;
        
        private System.Nullable<System.Guid> portalIdField;
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        private decimal priceField;
        
        private System.Nullable<int> orderField;
        
        private System.Nullable<int> qtyFromField;
        
        private System.Nullable<int> qtyToField;
        
        /// <remarks/>
        public System.Guid PricingOptionId {
            get {
                return this.pricingOptionIdField;
            }
            set {
                this.pricingOptionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ElementId {
            get {
                return this.elementIdField;
            }
            set {
                this.elementIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtyFrom {
            get {
                return this.qtyFromField;
            }
            set {
                this.qtyFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QtyTo {
            get {
                return this.qtyToField;
            }
            set {
                this.qtyToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Portal {
        
        private string portalNameField;
        
        private System.Guid portalIdField;
        
        private string membershipProviderNameField;
        
        private System.Nullable<bool> hTTPSField;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private System.Nullable<bool> defaultField;
        
        private string cultureField;
        
        private bool awaitingUpdateField;
        
        private System.Nullable<System.DateTime> autoDeleteDateField;
        
        /// <remarks/>
        public string PortalName {
            get {
                return this.portalNameField;
            }
            set {
                this.portalNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public string MembershipProviderName {
            get {
                return this.membershipProviderNameField;
            }
            set {
                this.membershipProviderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> HTTPS {
            get {
                return this.hTTPSField;
            }
            set {
                this.hTTPSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        public bool AwaitingUpdate {
            get {
                return this.awaitingUpdateField;
            }
            set {
                this.awaitingUpdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> AutoDeleteDate {
            get {
                return this.autoDeleteDateField;
            }
            set {
                this.autoDeleteDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductControlItem {
        
        private System.Nullable<System.Guid> portalIdField;
        
        private string nameField;
        
        private string itemLocXMLField;
        
        private System.Guid controlItemIdField;
        
        private Portal portalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemLocXML {
            get {
                return this.itemLocXMLField;
            }
            set {
                this.itemLocXMLField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ControlItemId {
            get {
                return this.controlItemIdField;
            }
            set {
                this.controlItemIdField = value;
            }
        }
        
        /// <remarks/>
        public Portal Portal {
            get {
                return this.portalField;
            }
            set {
                this.portalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PricingMedium {
        
        private System.Guid pricingMediaIdField;
        
        private System.Guid controlItemIdField;
        
        private System.Nullable<System.Guid> portalIdField;
        
        private decimal colourSingleSidedField;
        
        private decimal colourDoubleSidedField;
        
        private decimal monoSingleSidedField;
        
        private decimal monoDoubleSidedField;
        
        private decimal mediaCostField;
        
        private decimal laminatingCostField;
        
        private int printerTypeField;
        
        private int qtyToField;
        
        private int qtyFromField;
        
        private ProductControlItem productControlItemField;
        
        private Portal portalField;
        
        /// <remarks/>
        public System.Guid PricingMediaId {
            get {
                return this.pricingMediaIdField;
            }
            set {
                this.pricingMediaIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ControlItemId {
            get {
                return this.controlItemIdField;
            }
            set {
                this.controlItemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> PortalId {
            get {
                return this.portalIdField;
            }
            set {
                this.portalIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourSingleSided {
            get {
                return this.colourSingleSidedField;
            }
            set {
                this.colourSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal ColourDoubleSided {
            get {
                return this.colourDoubleSidedField;
            }
            set {
                this.colourDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoSingleSided {
            get {
                return this.monoSingleSidedField;
            }
            set {
                this.monoSingleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MonoDoubleSided {
            get {
                return this.monoDoubleSidedField;
            }
            set {
                this.monoDoubleSidedField = value;
            }
        }
        
        /// <remarks/>
        public decimal MediaCost {
            get {
                return this.mediaCostField;
            }
            set {
                this.mediaCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal LaminatingCost {
            get {
                return this.laminatingCostField;
            }
            set {
                this.laminatingCostField = value;
            }
        }
        
        /// <remarks/>
        public int PrinterType {
            get {
                return this.printerTypeField;
            }
            set {
                this.printerTypeField = value;
            }
        }
        
        /// <remarks/>
        public int QtyTo {
            get {
                return this.qtyToField;
            }
            set {
                this.qtyToField = value;
            }
        }
        
        /// <remarks/>
        public int QtyFrom {
            get {
                return this.qtyFromField;
            }
            set {
                this.qtyFromField = value;
            }
        }
        
        /// <remarks/>
        public ProductControlItem ProductControlItem {
            get {
                return this.productControlItemField;
            }
            set {
                this.productControlItemField = value;
            }
        }
        
        /// <remarks/>
        public Portal Portal {
            get {
                return this.portalField;
            }
            set {
                this.portalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAssemblyVersionCompletedEventHandler(object sender, GetAssemblyVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAssemblyVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAssemblyVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddMediaBandingItemCompletedEventHandler(object sender, AddMediaBandingItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddMediaBandingItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddMediaBandingItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteMediaItemsCompletedEventHandler(object sender, DeleteMediaItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMediaItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMediaItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddBandingItemCompletedEventHandler(object sender, AddBandingItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddBandingItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddBandingItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteItemsCompletedEventHandler(object sender, DeleteItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckGloalProductsCompletedEventHandler(object sender, CheckGloalProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckGloalProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckGloalProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOptionPriceCompletedEventHandler(object sender, GetOptionPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptionPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptionPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCustomOptionTitlesCompletedEventHandler(object sender, GetCustomOptionTitlesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomOptionTitlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomOptionTitlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomOptionTitle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomOptionTitle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateOptionPriceCompletedEventHandler(object sender, UpdateOptionPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOptionPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOptionPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FindMedisItemCompletedEventHandler(object sender, FindMedisItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindMedisItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindMedisItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PricingMedium Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PricingMedium)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PricingAddEditSingleMediaItemCompletedEventHandler(object sender, PricingAddEditSingleMediaItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PricingAddEditSingleMediaItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PricingAddEditSingleMediaItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdatePricingProductCompletedEventHandler(object sender, UpdatePricingProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePricingProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePricingProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOptionsByPortalCompletedEventHandler(object sender, GetOptionsByPortalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptionsByPortalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptionsByPortalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PricingOptions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PricingOptions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetMediaItemCompletedEventHandler(object sender, GetMediaItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMediaItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMediaItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PricingGetMediaItemResultSet[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PricingGetMediaItemResultSet[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOptionItemsCompletedEventHandler(object sender, GetOptionItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOptionItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOptionItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OptionCost[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OptionCost[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetMediaByPortalCompletedEventHandler(object sender, GetMediaByPortalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMediaByPortalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMediaByPortalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MediaCosting[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MediaCosting[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProductsByPortalCompletedEventHandler(object sender, GetProductsByPortalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsByPortalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsByPortalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductCost[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductCost[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddExistingPorductsCompletedEventHandler(object sender, AddExistingPorductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddExistingPorductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddExistingPorductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPortalGuidFromUrlCompletedEventHandler(object sender, GetPortalGuidFromUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPortalGuidFromUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPortalGuidFromUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UseHttpsCompletedEventHandler(object sender, UseHttpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UseHttpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UseHttpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool validUser {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public bool globalUser {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591